wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.15
    start_time: 1679143530.970004
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 77
      3:
      - 2
      - 16
      - 23
      4: 3.7.15
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
activation:
  desc: null
  value: tanh
architecture:
  desc: null
  value: Homo-GNN
channel type:
  desc: null
  value: TransConv
dataset:
  desc: null
  value: 1-HV-mixed--0-no_sw
dropout:
  desc: null
  value: 0.0
epochs:
  desc: null
  value: 400
hidden_channels:
  desc: null
  value: 186
in_channels:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.0001
norm:
  desc: null
  value: BatchNorm
num_layers:
  desc: null
  value: 4
output_channels:
  desc: null
  value: 4
scaler:
  desc: null
  value: StandardScaler()
